<div data-account-drawer hidden class="fixed inset-0 z-50 bg-slate-950/50">
    <aside class="absolute top-0 right-0 h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl">
        <header class="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4"><div><h2 class="text-xl font-bold">Minha conta</h2><p class="text-xs text-slate-500" data-account-subtitle>Entre para finalizar pedidos e acompanhar entregas</p></div><button type="button" data-close-account class="h-9 w-9 rounded-full bg-slate-100 text-xl">×</button></header>
        <div class="p-5">
            <div data-account-message hidden class="mb-4 rounded-lg px-3 py-2 text-sm"></div>
            <section data-account-guest>
                <div class="mb-5 flex rounded-xl bg-slate-100 p-1"><button type="button" data-auth-tab="login" class="flex-1 rounded-lg bg-white px-3 py-2 text-sm font-semibold shadow-sm">Entrar</button><button type="button" data-auth-tab="register" class="flex-1 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600">Criar conta</button></div>
                <form data-login-form class="space-y-3"><label class="block text-sm font-medium">E-mail ou WhatsApp<input name="identifier" autocomplete="username" required class="mt-1 w-full rounded-xl border p-3" placeholder="email@exemplo.com ou (24) 99999-9999"></label><label class="block text-sm font-medium">Senha<input name="password" type="password" autocomplete="current-password" required class="mt-1 w-full rounded-xl border p-3"></label><button class="w-full rounded-xl py-3 font-semibold text-white" style="background-color:{{ $themeColor }}">Entrar</button></form>
                <form data-register-form hidden class="space-y-3"><div class="grid gap-3 sm:grid-cols-2"><label class="block text-sm font-medium sm:col-span-2">Nome<input name="name" required class="mt-1 w-full rounded-xl border p-3"></label><label class="block text-sm font-medium">E-mail<input name="email" type="email" required class="mt-1 w-full rounded-xl border p-3"></label><label class="block text-sm font-medium">WhatsApp<input name="whatsapp" required class="mt-1 w-full rounded-xl border p-3"></label><label class="block text-sm font-medium sm:col-span-2">Senha<input name="password" type="password" minlength="6" required class="mt-1 w-full rounded-xl border p-3"></label></div><h3 class="pt-2 font-bold">Endereço principal</h3><input type="hidden" name="address_mode" value="cep"><div class="grid grid-cols-2 gap-3"><label class="block text-sm font-medium">CEP<input name="zip" required maxlength="10" data-register-zip class="mt-1 w-full rounded-xl border p-3"></label><label class="block text-sm font-medium">Número<input name="number" required maxlength="20" class="mt-1 w-full rounded-xl border p-3"></label><label class="col-span-2 block text-sm font-medium">Rua<input name="street" required class="mt-1 w-full rounded-xl border p-3"></label><label class="block text-sm font-medium">Bairro<input name="neighborhood" required class="mt-1 w-full rounded-xl border p-3"></label><label class="block text-sm font-medium">Cidade<input name="city" required class="mt-1 w-full rounded-xl border p-3"></label><label class="block text-sm font-medium">Estado<input name="state" required maxlength="2" class="mt-1 w-full rounded-xl border p-3 uppercase"></label><label class="block text-sm font-medium">Complemento<input name="complement" class="mt-1 w-full rounded-xl border p-3"></label><label class="col-span-2 block text-sm font-medium">Referência<input name="reference" class="mt-1 w-full rounded-xl border p-3"></label></div><button class="w-full rounded-xl py-3 font-semibold text-white" style="background-color:{{ $themeColor }}">Criar conta e continuar</button></form>
            </section>
            <section data-account-auth hidden>
                <div class="flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><strong data-customer-name></strong><p class="text-sm text-slate-500" data-customer-contact></p></div><button type="button" data-customer-logout class="rounded-lg border bg-white px-3 py-2 text-sm">Sair</button></div>
                <div class="mt-5 flex gap-2 border-b"><button data-account-tab="orders" class="border-b-2 px-3 py-2 text-sm font-semibold" style="border-color:{{ $themeColor }}">Pedidos</button><button data-account-tab="addresses" class="px-3 py-2 text-sm font-semibold text-slate-500">Endereços</button></div>
                <div data-orders-panel class="mt-4 space-y-3"><p class="py-5 text-center text-sm text-slate-500">Carregando pedidos...</p></div>
                <div data-addresses-panel hidden class="mt-4"><div data-address-list class="space-y-3"></div><button type="button" data-show-address-form class="mt-3 rounded-lg border px-3 py-2 text-sm font-semibold">Adicionar endereço</button><form data-address-form hidden class="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4"><input name="label" placeholder="Nome (Casa, Trabalho)" class="col-span-2 rounded-lg border p-2"><input name="zip" required placeholder="CEP" class="rounded-lg border p-2"><input name="number" required placeholder="Número" class="rounded-lg border p-2"><input name="street" required placeholder="Rua" class="col-span-2 rounded-lg border p-2"><input name="neighborhood" required placeholder="Bairro" class="rounded-lg border p-2"><input name="city" required placeholder="Cidade" class="rounded-lg border p-2"><input name="state" required maxlength="2" placeholder="UF" class="rounded-lg border p-2 uppercase"><input name="complement" placeholder="Complemento" class="rounded-lg border p-2"><input name="reference" placeholder="Referência" class="col-span-2 rounded-lg border p-2"><label class="col-span-2 flex items-center gap-2 text-sm"><input name="is_default" type="checkbox" value="1"> Tornar endereço principal</label><button class="col-span-2 rounded-lg py-2 font-semibold text-white" style="background-color:{{ $themeColor }}">Salvar endereço</button></form></div>
            </section>
        </div>
    </aside>
</div>
